# Generated by Django 4.0.2 on 2024-02-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('cpf_cliente', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=200)),
                ('especie_pet', models.CharField(max_length=200)),
                ('sexo_pet', models.CharField(max_length=15)),
                ('cor_pet', models.CharField(max_length=20)),
                ('idade_pet', models.IntegerField()),
                ('peso_pet', models.FloatField()),
                ('cliente_pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.cadastrocliente')),
            ],
        ),
    ]
